### ISSUE TITLE
Exception on windows

### ISSUE THREAD

**Issue by JakevK** [ryan-mooore/topomc#1]
`````
$ pipenv run python topomc 0 0 5 5
11768-INFO-App: No world found, using default
11768-CRITICAL-Yaml: settings.yml is incorrectly formatted or missing
Traceback (most recent call last):
  File "topomc\app.py", line 47, in run
    world = args[5]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "topomc\__main__.py", line 7, in <module>
    app.run(sys.argv)
  File "topomc\app.py", line 50, in run
    world = yaml_open.get("world")
  File "topomc\common\yaml_open.py", line 17, in get
    raise e
  File "topomc\common\yaml_open.py", line 8, in get
    settings = yaml.full_load(stream)
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\__init__.py", line 142, in full_load
    return load(stream, FullLoader)
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\User\.virtualenvs\topomc-OaAVHX4V\lib\site-packages\yaml\scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '%' that cannot start any token
  in "settings.yml", line 2, column 13

**Comment by ryan-mooore** [comment]
fixed in 05989ab
